-- WQTD EMPLOYEE NAME , MANAGER NAME , EMPLOYEE SAL , MANAGER SAL IF EMPLOYEE ARE HIRED AFTER YEAR 80 GETTING SAL GREATER THAN 1200 AND LESS THAN EQUAL TO 200 AND MANAGER HIRED BEFORE YEAR 88.--

 SELECT E.ENAME , M.ENAME , E.SAL , M .SAL 
 FROM EMP E , EMP M 
 WHERE E.MGR = M. EMPNO 
 AND 
 E.SAL NOT BETWEEN 201 AND 1200 
 AND E.HIREDATE <'01-JAN-88';
