-- WQTD ALL THE DETAILS OF EMPLOYEE WHO ARE REPORTING TO KING GETTING SALARY GREATER THAN ALLEN AND LESS THAN  FORD HIRED AFTER FIRST EMPLOYEE. 

 SELECT * FROM EMP
 WHERE MGR = ( SELECT EMPNO
 FROM EMP WHERE ENAME = 'KING')
 AND SAL > ( SELECT SAL FROM EMP
 WHERE ENAME = 'ALLEN') AND SAL < (SELECT SAL FROM EMP
 WHERE ENAME ='FORD')
 ORDER BY HIREDATE
